### ISSUE TITLE
Giving ground truth pose parameter to RaBit model result in an odd pose

### ISSUE THREAD

**Issue by ujey02** [zhongjinluo/RaBit#2]
In the 3DBiCar dataset, there are beta and pose parameters in npy
When those parameters are given to RaBit model, it results like below.
Seems that shape is similar to the image but the pose is totally off from the original. 
Since the pose.npy contains parameters in (24,3) dimension and RaBit takes (23,3) shape data for pose,
I sliced the array into (:1,3) and (1:,3) for trans and pose. Maybe I have to slice in different way? 
Could you clarify how to process the given npy file and appropriately fed it to RaBit model to produce a pose similar to the input image?   

![image](https://github.com/zhongjinluo/RaBit/assets/16874938/7bff0775-e44b-400b-bd77-b43738cc36fd)

**Comment by zhongjinluo** [comment]
We have fixed this bug. Please check out [rabit_np.py](https://github.com/zhongjinluo/RaBit/blob/master/rabit_np.py) and [rabit_torch.py](https://github.com/zhongjinluo/RaBit/blob/master/rabit_torch.py).

**Comment by ujey02** [comment]
Thank you!
