### ISSUE TITLE
The dataset on OneDrive is hard to download, always interrupted

### ISSUE THREAD

**Issue by SYL-322** [zhongjinluo/RaBit#5]
Hi,

Thank you for your great work!
I want to use your dataset, but the download process on OneDrive is easily interrupted and cannot be resumed. I've tried several times but still no success. Can you provide a download version of GoogleDrive?

**Comment by zhongjinluo** [comment]
Please try:
https://pan.baidu.com/s/1gMHhMUKNepOk2cxlPkQm4Q 
password: GAPL

**Comment by SYL-322** [comment]
Thank you!!
